# docker network create "devnet"
networks:
  devnet:
    name: devnet
    external: true

volumes:
  postgres_data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/run/media/bcueva/volumes/volume/postgres'

services:
  postgres:
      image: postgres:16.2
      container_name: postgres
      ports:
      - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      networks:
      - devnet
