# Documentation https://hub.docker.com/_/postgres/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm-postgres
  namespace: databases
  labels:
    app: dpm-postgres
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: dpm-postgres
  template:
    metadata:
      labels:
        app: dpm-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.5-alpine3.22
          resources:
            limits:
              cpu: 4000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 250Mi
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: sct-postgres
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sct-postgres
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sct-postgres
                  key: db_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: vlm-nfs-postgres
      volumes:
        - name: vlm-nfs-postgres
          persistentVolumeClaim:
            claimName: pvc-postgres
