apiVersion: v1
kind: Service
metadata:
  name: sv-db-postgres
  namespace: databases
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      protocol: TCP
  externalIPs:
    - 192.168.1.17
  selector:
    app: dpm-db-postgres