apiVersion: v1
kind: Service
metadata:
  name: sv-postgres
  namespace: databases
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      protocol: TCP
  #externalIPs:
  #  - 192.168.1.6
  selector:
    app: dpm-postgres