apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: apps
  labels: {app: demo}
spec:
  replicas: 1
  selector: {matchLabels: {app: demo}}
  template:
    metadata: {labels: {app: demo}}
    spec:
      containers:
        - name: demo
          image: hashicorp/http-echo
          args: ["-text=hola lan"]
          ports: [{containerPort: 5678}]
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: apps
spec:
  selector: {app: demo}
  ports: [{port: 80, targetPort: 5678}]
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: {name: demo, port: {number: 80}}
