apiVersion: v1
kind: PersistentVolume
metadata:
  name: vlm-db-postgres
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /run/media/bcueva/volumes/k8s/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1
  