services:
  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/server-cert.pem:/etc/nginx/ssl/cert.pem
      - ./config/server-key.pem:/etc/nginx/ssl/key.pem
      - ./config/nginx.conf:/etc/nginx/nginx.conf 