apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster-postgresql-instance2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 280Gi
  nfs:
    path: /postgresql/cluster-data/instance2
    server: storage
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-cluster-postgres
  volumeMode: Filesystem
