apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster-postgresql-instance3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 280Gi
  nfs:
    path: /postgresql/cluster-data/instance3
    server: strorage
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-cluster-postgres
  volumeMode: Filesystem
