apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: databases
spec:
  storageClassName: sc-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi